[2023-08-29T23:24:13.141+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=second_group.inner_function2 permission to 509
[2023-08-29T23:24:13.143+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=second_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=second_group.inner_function2'
[2023-08-29T23:24:13.189+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=second_group.inner_function2 permission to 509
[2023-08-29T23:24:13.190+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=second_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=second_group.inner_function2'
[2023-08-29T23:24:13.349+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_python_with_task_group.second_group.inner_function2 manual__2023-08-29T23:24:04.299332+00:00 [queued]>
[2023-08-29T23:24:13.359+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_python_with_task_group.second_group.inner_function2 manual__2023-08-29T23:24:04.299332+00:00 [queued]>
[2023-08-29T23:24:13.360+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-29T23:24:13.396+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): second_group.inner_function2> on 2023-08-29 23:24:04.299332+00:00
[2023-08-29T23:24:13.402+0000] {standard_task_runner.py:57} INFO - Started process 187 to run task
[2023-08-29T23:24:13.406+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_python_with_task_group', 'second_group.inner_function2', 'manual__2023-08-29T23:24:04.299332+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_with_task_group.py', '--cfg-path', '/tmp/tmpfg8qltjj']
[2023-08-29T23:24:13.409+0000] {standard_task_runner.py:85} INFO - Job 176: Subtask second_group.inner_function2
[2023-08-29T23:24:13.489+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=second_group.inner_function2 permission to 509
[2023-08-29T23:24:13.490+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=second_group.inner_function2 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_with_task_group/run_id=manual__2023-08-29T23:24:04.299332+00:00/task_id=second_group.inner_function2'
[2023-08-29T23:24:13.493+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_python_with_task_group.second_group.inner_function2 manual__2023-08-29T23:24:04.299332+00:00 [running]> on host 07fcf706bef2
[2023-08-29T23:24:13.660+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dags_python_with_task_group' AIRFLOW_CTX_TASK_ID='second_group.inner_function2' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T23:24:04.299332+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T23:24:04.299332+00:00'
[2023-08-29T23:24:13.663+0000] {logging_mixin.py:150} INFO - 두 번째 TaskGroup내 두 번째 task입니다.
[2023-08-29T23:24:13.663+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-29T23:24:13.676+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=dags_python_with_task_group, task_id=second_group.inner_function2, execution_date=20230829T232404, start_date=20230829T232413, end_date=20230829T232413
[2023-08-29T23:24:13.738+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-29T23:24:13.759+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
