[2023-08-28T19:45:42.214+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_pull permission to 509
[2023-08-28T19:45:42.215+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_pull permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_pull'
[2023-08-28T19:45:42.259+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_pull permission to 509
[2023-08-28T19:45:42.260+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_pull permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_pull'
[2023-08-28T19:45:42.401+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_pull scheduled__2023-08-27T00:10:00+00:00 [queued]>
[2023-08-28T19:45:42.410+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_bash_with_xcom.bash_pull scheduled__2023-08-27T00:10:00+00:00 [queued]>
[2023-08-28T19:45:42.410+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-28T19:45:42.445+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): bash_pull> on 2023-08-27 00:10:00+00:00
[2023-08-28T19:45:42.463+0000] {standard_task_runner.py:57} INFO - Started process 87 to run task
[2023-08-28T19:45:42.467+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_bash_with_xcom', 'bash_pull', 'scheduled__2023-08-27T00:10:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/dags_bash_with_xcom.py', '--cfg-path', '/tmp/tmpllhhv0ae']
[2023-08-28T19:45:42.469+0000] {standard_task_runner.py:85} INFO - Job 100: Subtask bash_pull
[2023-08-28T19:45:42.535+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_pull permission to 509
[2023-08-28T19:45:42.536+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_pull permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_bash_with_xcom/run_id=scheduled__2023-08-27T00:10:00+00:00/task_id=bash_pull'
[2023-08-28T19:45:42.538+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_bash_with_xcom.bash_pull scheduled__2023-08-27T00:10:00+00:00 [running]> on host 07fcf706bef2
[2023-08-28T19:45:42.656+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'bash_pull', field 'env'. Template: {'PUSHED_VALUE': "{{ ti.xcom_pull(key='bash_pushed') }}", 'RETURN_VALUE': "{{ ti.xcom_pull(task_id='bash_push') }}"}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 298, in call
    return __obj(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2023-08-28T19:45:42.665+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 298, in call
    return __obj(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2023-08-28T19:45:42.673+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dags_bash_with_xcom, task_id=bash_pull, execution_date=20230827T001000, start_date=20230828T194542, end_date=20230828T194542
[2023-08-28T19:45:42.707+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 100 for task bash_pull (xcom_pull() got an unexpected keyword argument 'task_id'; 87)
[2023-08-28T19:45:42.719+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-28T19:45:42.735+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
