[2023-08-29T03:36:03.058+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:36:03.059+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_branch_python_operator.py for tasks to queue
[2023-08-29T03:36:03.061+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:36:03.060+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:36:03.105+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:36:03.097+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_branch_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_branch_python_operator.py", line 9, in <module>
    start_date = datetime(2023,8,1,tz="UTC"),
TypeError: 'module' object is not callable
[2023-08-29T03:36:03.108+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:36:03.150+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_branch_python_operator.py took 0.096 seconds
[2023-08-29T03:36:33.828+0000] {processor.py:157} INFO - Started process (PID=122) to work on /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:36:33.829+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_branch_python_operator.py for tasks to queue
[2023-08-29T03:36:33.830+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:36:33.830+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:36:33.857+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:36:33.852+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_branch_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_branch_python_operator.py", line 9, in <module>
    start_date = datetime(2023,8,1,tz="UTC"),
TypeError: 'module' object is not callable
[2023-08-29T03:36:33.859+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:36:33.895+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_branch_python_operator.py took 0.071 seconds
[2023-08-29T03:37:04.404+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:37:04.405+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_branch_python_operator.py for tasks to queue
[2023-08-29T03:37:04.407+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:37:04.406+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:37:04.435+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:37:04.429+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_branch_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_branch_python_operator.py", line 9, in <module>
    start_date = datetime(2023,8,1,tz="UTC"),
TypeError: 'module' object is not callable
[2023-08-29T03:37:04.438+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:37:04.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_branch_python_operator.py took 0.074 seconds
[2023-08-29T03:37:24.347+0000] {processor.py:157} INFO - Started process (PID=297) to work on /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:37:24.349+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_branch_python_operator.py for tasks to queue
[2023-08-29T03:37:24.351+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:37:24.351+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:37:24.413+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:37:24.406+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_branch_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_branch_python_operator.py", line 9, in <module>
    start_date = datetime(2023,8,1),
TypeError: 'module' object is not callable
[2023-08-29T03:37:24.415+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:37:24.453+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_branch_python_operator.py took 0.111 seconds
[2023-08-29T03:37:54.960+0000] {processor.py:157} INFO - Started process (PID=388) to work on /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:37:54.961+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_branch_python_operator.py for tasks to queue
[2023-08-29T03:37:54.962+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:37:54.961+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:37:54.992+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:37:54.986+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_branch_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_branch_python_operator.py", line 9, in <module>
    start_date = datetime(2023,8,1),
TypeError: 'module' object is not callable
[2023-08-29T03:37:54.995+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:37:55.067+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_branch_python_operator.py took 0.111 seconds
[2023-08-29T03:38:25.763+0000] {processor.py:157} INFO - Started process (PID=479) to work on /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:38:25.764+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_branch_python_operator.py for tasks to queue
[2023-08-29T03:38:25.765+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:38:25.765+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:38:25.794+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:38:25.789+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_branch_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_branch_python_operator.py", line 9, in <module>
    start_date = datetime(2023,8,1),
TypeError: 'module' object is not callable
[2023-08-29T03:38:25.796+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:38:25.876+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_branch_python_operator.py took 0.116 seconds
[2023-08-29T03:38:56.518+0000] {processor.py:157} INFO - Started process (PID=570) to work on /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:38:56.520+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_branch_python_operator.py for tasks to queue
[2023-08-29T03:38:56.522+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:38:56.521+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:38:56.549+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:38:56.544+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_branch_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_branch_python_operator.py", line 9, in <module>
    start_date = datetime(2023,8,1),
TypeError: 'module' object is not callable
[2023-08-29T03:38:56.551+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:38:56.589+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_branch_python_operator.py took 0.074 seconds
[2023-08-29T03:39:26.819+0000] {processor.py:157} INFO - Started process (PID=661) to work on /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:39:26.820+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_branch_python_operator.py for tasks to queue
[2023-08-29T03:39:26.821+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:39:26.821+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:39:26.853+0000] {logging_mixin.py:150} INFO - [2023-08-29T03:39:26.846+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_branch_python_operator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_branch_python_operator.py", line 9, in <module>
    start_date = datetime(2023,8,1),
TypeError: 'module' object is not callable
[2023-08-29T03:39:26.855+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_branch_python_operator.py
[2023-08-29T03:39:26.896+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_branch_python_operator.py took 0.081 seconds
