[2023-08-28T22:07:33.444+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_email_operator/run_id=manual__2023-08-28T22:07:29.608213+00:00/task_id=send_email permission to 509
[2023-08-28T22:07:33.445+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_email_operator/run_id=manual__2023-08-28T22:07:29.608213+00:00/task_id=send_email permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_email_operator/run_id=manual__2023-08-28T22:07:29.608213+00:00/task_id=send_email'
[2023-08-28T22:07:33.489+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_email_operator/run_id=manual__2023-08-28T22:07:29.608213+00:00/task_id=send_email permission to 509
[2023-08-28T22:07:33.490+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_email_operator/run_id=manual__2023-08-28T22:07:29.608213+00:00/task_id=send_email permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_email_operator/run_id=manual__2023-08-28T22:07:29.608213+00:00/task_id=send_email'
[2023-08-28T22:07:33.650+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dags_python_email_operator.send_email manual__2023-08-28T22:07:29.608213+00:00 [queued]>
[2023-08-28T22:07:33.661+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dags_python_email_operator.send_email manual__2023-08-28T22:07:29.608213+00:00 [queued]>
[2023-08-28T22:07:33.662+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-28T22:07:33.697+0000] {taskinstance.py:1327} INFO - Executing <Task(EmailOperator): send_email> on 2023-08-28 22:07:29.608213+00:00
[2023-08-28T22:07:33.703+0000] {standard_task_runner.py:57} INFO - Started process 850 to run task
[2023-08-28T22:07:33.706+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dags_python_email_operator', 'send_email', 'manual__2023-08-28T22:07:29.608213+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/dags_python_email_operator.py', '--cfg-path', '/tmp/tmpoml9ks_1']
[2023-08-28T22:07:33.709+0000] {standard_task_runner.py:85} INFO - Job 114: Subtask send_email
[2023-08-28T22:07:33.799+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=dags_python_email_operator/run_id=manual__2023-08-28T22:07:29.608213+00:00/task_id=send_email permission to 509
[2023-08-28T22:07:33.799+0000] {logging_mixin.py:150} INFO - Failed to change /opt/***/logs/dag_id=dags_python_email_operator/run_id=manual__2023-08-28T22:07:29.608213+00:00/task_id=send_email permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=dags_python_email_operator/run_id=manual__2023-08-28T22:07:29.608213+00:00/task_id=send_email'
[2023-08-28T22:07:33.802+0000] {task_command.py:410} INFO - Running <TaskInstance: dags_python_email_operator.send_email manual__2023-08-28T22:07:29.608213+00:00 [running]> on host 07fcf706bef2
[2023-08-28T22:07:33.899+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'send_email', field 'html_content'. Template: '{{ data_intrval_end | ds }} 처리 결과 <br> 알루는 {{ ti.xcom_pull(task_ids="find_dog_task")}} 입니다. <br>'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 19, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/templates.py", line 54, in ds_filter
    return value.strftime("%Y-%m-%d")
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_intrval_end' is undefined
[2023-08-28T22:07:33.903+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 19, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/templates.py", line 54, in ds_filter
    return value.strftime("%Y-%m-%d")
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'data_intrval_end' is undefined
[2023-08-28T22:07:33.910+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=dags_python_email_operator, task_id=send_email, execution_date=20230828T220729, start_date=20230828T220733, end_date=20230828T220733
[2023-08-28T22:07:33.977+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 114 for task send_email ('data_intrval_end' is undefined; 850)
[2023-08-28T22:07:33.999+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-28T22:07:34.022+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
